import type { Question } from '../types/session';

export const QUESTIONS: Record<string, Question[]> = {
  founder: [
    {
      id: 'name',
      sect: 'The Big Picture',
      type: 'text',
      text: "What's the name of the software you want to build?",
      hint: "Don't worry if it's not final.",
      ex: {
        l: 'Examples',
        t: '"Intake" / "ColdCase" / "WitnessLink" / "Evidence Vault"',
      },
    },
    {
      id: 'summary',
      sect: 'The Big Picture',
      type: 'textarea',
      text: "Describe your product in plain language -- like you're telling a friend with no tech background.",
      hint: 'What does it do, for whom, and why does it matter?',
      ex: {
        l: 'Example',
        t: '"ColdCase helps detectives keep track of old unsolved crimes in one place, so they can pick a case back up years later without losing anything."',
      },
    },
    {
      id: 'problem',
      sect: 'The Big Picture',
      type: 'textarea',
      text: 'What painful problem does this solve today? What happens without it?',
      ex: {
        l: 'Example',
        t: '"Cold case files sit in storage boxes. When a detective retires, their knowledge walks out the door."',
      },
    },
    {
      id: 'who_uses',
      sect: 'Who Uses It',
      type: 'textarea',
      text: 'Who are the different types of people who will use this? List each type and what they need to do.',
      ex: {
        l: 'Example',
        t: '"Lead detectives -- enter and manage case info. Supervisors -- review all cases. Records staff -- upload old paper files."',
      },
    },
    {
      id: 'workflow',
      sect: 'How It Works',
      type: 'textarea',
      text: 'Describe the step-by-step process a user follows when using this system from start to finish.',
      hint: 'Walk through what someone actually does -- step by step, in order.',
      ex: {
        l: 'Example',
        t: '"Officer opens a case -> enters incident facts -> system analyzes statutes -> system suggests charges -> prosecutor confirms -> officer proceeds."',
      },
    },
    {
      id: 'must_haves',
      sect: 'What It Does',
      type: 'textarea',
      text: 'List the features this product must have on day one. Without these, it does not work.',
      ex: {
        l: 'Example',
        t: '"Search by suspect name or case number. Attach photos and documents. Timeline of events. Assign cases to detectives."',
      },
    },
    {
      id: 'nice_to_haves',
      sect: 'What It Does',
      type: 'textarea',
      text: "What would you love eventually but don't need for the first version?",
      ex: {
        l: 'Example',
        t: '"AI that finds connections between cases. Public tip portal. Mobile app for field use."',
      },
      required: false,
    },
    {
      id: 'not_allowed',
      sect: 'What It Does',
      type: 'textarea',
      text: 'Is there anything this system should specifically NOT do? Any hard limits?',
      ex: {
        l: 'Example',
        t: '"Should never automatically decide charges. Should never share case info outside the agency without supervisor approval."',
      },
      required: false,
    },
    {
      id: 'edge_cases',
      sect: 'What It Does',
      type: 'textarea',
      text: 'What unusual or complicated situations could occur when using this system?',
      hint: "Think about the hard cases -- ones that don't fit the normal workflow.",
      ex: {
        l: 'Example',
        t: '"Multiple suspects in one incident. Juvenile suspects. Conflicting witness statements. Officer loses internet connection in the field."',
      },
      required: false,
    },
    {
      id: 'who_approves',
      sect: 'The Organization',
      type: 'textarea',
      text: 'Who needs to approve this before it can launch or be purchased?',
      ex: {
        l: 'Example',
        t: '"Our CEO, lead developer, the Sheriff\'s IT security officer, and county legal."',
      },
    },
    {
      id: 'timeline',
      sect: 'The Organization',
      type: 'textarea',
      text: 'Is there a deadline or important milestone driving when this needs to be ready?',
      ex: {
        l: 'Example',
        t: '"We have a DOJ grant requiring a working demo by September. Pilot agency wants to test in Q4."',
      },
      required: false,
    },
    {
      id: 'success',
      sect: 'The Organization',
      type: 'textarea',
      text: 'How will you know this product is actually working and making a difference?',
      ex: {
        l: 'Example',
        t: '"Cases re-opened 50% faster. Detectives spend less time searching archives."',
      },
    },
    {
      id: 'concerns',
      sect: 'The Organization',
      type: 'textarea',
      text: 'What are you most worried about -- technical, legal, political, or practical?',
      ex: {
        l: 'Example',
        t: '"Worried about agencies changing habits. Unsure how to handle data from agencies in different states."',
      },
      required: false,
    },
  ],
  pm: [
    {
      id: 'name',
      sect: 'Product Identity',
      type: 'text',
      text: 'Product name and version scope',
      ex: {
        l: 'Example',
        t: '"Intake -- Pre-Arrest Screening Tool, V1.0 (pilot release)"',
      },
    },
    {
      id: 'summary',
      sect: 'Product Identity',
      type: 'textarea',
      text: 'Executive summary: product vision, target users, and core value proposition',
    },
    {
      id: 'personas',
      sect: 'Users & Personas',
      type: 'textarea',
      text: 'Define each user persona: role, goals, pain points, tech comfort, usage frequency',
      ex: {
        l: 'Example',
        t: '"Lead Detective: 8-12 active cases. Goals: quick evidence access. Pain: paper archives. Tech: moderate. Usage: daily."',
      },
    },
    {
      id: 'workflow',
      sect: 'Users & Personas',
      type: 'textarea',
      text: 'Describe the step-by-step process a user follows when using this system from start to finish.',
      hint: 'Map the primary workflow end-to-end. Include key decision points.',
      ex: {
        l: 'Example',
        t: '"Officer opens a case -> enters incident facts -> system suggests charges -> prosecutor confirms -> officer proceeds with arrest or release."',
      },
    },
    {
      id: 'must_haves',
      sect: 'Functional Requirements',
      type: 'textarea',
      text: 'All must-have functional requirements for V1, grouped by feature area',
      ex: {
        l: 'Example',
        t: '"Case Mgmt: create/edit/archive, attach evidence, status workflow. Search: full-text across all fields, filter by status/detective/date."',
      },
    },
    {
      id: 'business_rules',
      sect: 'Functional Requirements',
      type: 'textarea',
      text: 'What rules determine what the system recommends, flags, blocks, or requires?',
      hint: 'Think about automated logic, thresholds, and decision triggers.',
      ex: {
        l: 'Example',
        t: '"If BAC > .08 -> recommend DWI charge. If firearm present -> flag charge enhancement. If suspect is juvenile -> require supervisor approval."',
      },
    },
    {
      id: 'key_entities',
      sect: 'Functional Requirements',
      type: 'textarea',
      text: 'What are the primary things the system stores, tracks, or manages? List the core objects.',
      hint: 'These become your database tables and API resources.',
      ex: {
        l: 'Example',
        t: '"Case / Officer / Suspect / Evidence / Statute / Charge / Report / Agency"',
      },
    },
    {
      id: 'failure_modes',
      sect: 'Functional Requirements',
      type: 'textarea',
      text: 'What system failures must be handled safely and gracefully?',
      hint: 'What should happen when things go wrong -- not just when they work.',
      ex: {
        l: 'Example',
        t: '"Network outage during submission. Database unavailable. Evidence upload failure. Authentication timeout mid-session."',
      },
    },
    {
      id: 'nice_to_haves',
      sect: 'Functional Requirements',
      type: 'textarea',
      text: 'Phase 2 and backlog items -- features deferred from V1 with rationale',
      required: false,
    },
    {
      id: 'not_allowed',
      sect: 'Functional Requirements',
      type: 'textarea',
      text: 'Out of scope items and hard exclusions -- what this system must never do',
    },
    {
      id: 'integrations',
      sect: 'Integrations',
      type: 'textarea',
      text: 'Required integrations: systems, APIs, data sources this must connect to',
      ex: {
        l: 'Example',
        t: '"Tyler RMS (read, required) / NCIC (read, required) / AD/SSO (auth, required)"',
      },
    },
    {
      id: 'nfr',
      sect: 'Non-Functional Requirements',
      type: 'textarea',
      text: 'Performance, availability, scalability, accessibility requirements with measurable targets',
      ex: {
        l: 'Example',
        t: '"Search < 2s at p95. 99.5% uptime business hours. 50 concurrent users at launch. WCAG 2.1 AA."',
      },
    },
    {
      id: 'compliance',
      sect: 'Compliance',
      type: 'multi',
      text: 'Which compliance frameworks apply? Select all that are relevant.',
      choices: [
        'CJIS Security Policy',
        'FedRAMP',
        'StateRAMP',
        'CISA CPGs',
        'CMMC',
        'TX-RAMP',
        'HIPAA',
        'SOC 2 Type II',
        'Not sure yet',
      ],
    },
    {
      id: 'auth_access',
      sect: 'Security',
      type: 'textarea',
      text: 'Authentication, authorization, and access control requirements',
    },
    {
      id: 'audit',
      sect: 'Security',
      type: 'textarea',
      text: 'Audit logging, data retention, and legal hold requirements',
    },
    {
      id: 'stakeholders',
      sect: 'Governance',
      type: 'textarea',
      text: 'Stakeholder matrix: who approves, reviews, and is informed',
    },
    {
      id: 'timeline',
      sect: 'Governance',
      type: 'textarea',
      text: 'Timeline, milestones, and budget constraints',
    },
    {
      id: 'risks',
      sect: 'Governance',
      type: 'textarea',
      text: 'Known risks, assumptions, and dependencies',
      required: false,
    },
  ],
  developer: [
    {
      id: 'name',
      sect: 'Scope',
      type: 'text',
      text: 'Product name and build scope',
      ex: {
        l: 'Example',
        t: '"ColdCase -- V1 backend API + React web frontend"',
      },
    },
    {
      id: 'summary',
      sect: 'Scope',
      type: 'textarea',
      text: 'Technical summary: what this system does, primary data flows',
    },
    {
      id: 'key_entities',
      sect: 'Scope',
      type: 'textarea',
      text: 'What are the primary things the system stores, tracks, or manages? List core data objects and key relationships.',
      ex: {
        l: 'Example',
        t: '"Case / Officer / Suspect / Evidence / Statute / Charge / Report. Case has many Evidence; soft-delete and audit columns on all entities."',
      },
    },
    {
      id: 'tech_stack',
      sect: 'Architecture',
      type: 'textarea',
      text: 'Required, preferred, or prohibited technology stack',
      ex: {
        l: 'Example',
        t: '"Frontend: React+TypeScript. Backend: Node/FastAPI. DB: PostgreSQL. Cloud: AWS GovCloud. No Google Cloud per agency policy."',
      },
    },
    {
      id: 'scale',
      sect: 'Architecture',
      type: 'textarea',
      text: 'Scale: concurrent users, data volume, growth, multi-tenancy needs',
      ex: {
        l: 'Example',
        t: '"V1: 50 concurrent, 3 agencies. V2: 500 concurrent, 50 agencies, multi-tenant with logical data isolation."',
      },
    },
    {
      id: 'performance',
      sect: 'Architecture',
      type: 'textarea',
      text: 'Performance SLOs: latency targets, throughput, error budgets',
      ex: {
        l: 'Example',
        t: '"API p95 < 300ms. Search p95 < 1s. 99.5% availability. RTO < 4hr, RPO < 1hr."',
      },
    },
    {
      id: 'business_rules',
      sect: 'Architecture',
      type: 'textarea',
      text: 'What rules determine what the system recommends, flags, blocks, or requires?',
      hint: 'These become backend validation rules or rule engines.',
      ex: {
        l: 'Example',
        t: '"If BAC > .08 -> recommend DWI. If firearm present -> flag enhancement. Juvenile suspects -> escalation workflow."',
      },
    },
    {
      id: 'failure_modes',
      sect: 'Architecture',
      type: 'textarea',
      text: 'What system failures must be handled safely? Define expected error handling.',
      ex: {
        l: 'Example',
        t: '"Network outage: queue locally, sync on reconnect. DB unavailable: read-only cache mode."',
      },
    },
    {
      id: 'integrations',
      sect: 'Integrations',
      type: 'textarea',
      text: 'External systems: protocols, auth methods, data formats',
      ex: {
        l: 'Example',
        t: '"NCIC: REST/OAuth2/JSON. Tyler RMS: SOAP/NTLM. AD/LDAP for SSO. S3-compatible for evidence files."',
      },
    },
    {
      id: 'security',
      sect: 'Security & Compliance',
      type: 'textarea',
      text: 'Security architecture: auth, encryption standards, network controls, audit trail, RBAC design',
    },
    {
      id: 'compliance',
      sect: 'Security & Compliance',
      type: 'multi',
      text: 'Applicable compliance frameworks',
      choices: [
        'CJIS Security Policy',
        'FedRAMP Moderate',
        'FedRAMP High',
        'StateRAMP',
        'CISA CPGs',
        'CMMC Level 2',
        'CMMC Level 3',
        'TX-RAMP',
        'HIPAA',
        'SOC 2 Type II',
        'NIST 800-53',
      ],
    },
    {
      id: 'data_model',
      sect: 'Data',
      type: 'textarea',
      text: 'Core data entities, relationships, schema constraints',
      ex: {
        l: 'Example',
        t: '"Entities: Agency, User, Case, Evidence, Suspect, Person, Timeline. All need soft delete + audit columns."',
      },
    },
    {
      id: 'data_types',
      sect: 'Data',
      type: 'textarea',
      text: 'File/media types, storage requirements, size constraints, chain of custody needs',
      ex: {
        l: 'Example',
        t: '"Images (<=50MB), video (<=2GB), PDF/DOCX. Evidence immutable after submission. SHA-256 checksums required."',
      },
    },
    {
      id: 'edge_cases',
      sect: 'Constraints',
      type: 'textarea',
      text: 'What unusual or complicated situations must the system handle correctly?',
      ex: {
        l: 'Example',
        t: '"Multiple suspects on one incident. Concurrent edits by two officers. Partial upload on slow connection."',
      },
    },
    {
      id: 'constraints',
      sect: 'Constraints',
      type: 'textarea',
      text: 'Browser support, network environment, device requirements, offline needs',
    },
    {
      id: 'must_haves',
      sect: 'Functional Scope',
      type: 'textarea',
      text: 'V1 functional scope -- what must be built vs. explicitly deferred',
    },
    {
      id: 'risks',
      sect: 'Functional Scope',
      type: 'textarea',
      text: 'Technical risks, unknowns, dependencies that could affect delivery',
      required: false,
    },
  ],
  leo: [
    {
      id: 'name',
      sect: 'About the Tool',
      type: 'text',
      text: 'What do you call this tool, or what would you like it to be called?',
    },
    {
      id: 'summary',
      sect: 'About the Tool',
      type: 'textarea',
      text: 'In your own words, what should this software help you do?',
      ex: {
        l: 'Example',
        t: '"Pull up everything we know about a suspect or a case in one place, without digging through a dozen different systems."',
      },
    },
    {
      id: 'daily_pain',
      sect: 'The Problem Today',
      type: 'textarea',
      text: "What's your biggest frustration with how things work today -- without this tool?",
      ex: {
        l: 'Example',
        t: '"Every time I pick up a cold case I spend two days figuring out what was already done."',
      },
    },
    {
      id: 'daily_workflow',
      sect: 'The Problem Today',
      type: 'textarea',
      text: 'Walk me through a key workflow step by step -- what actually happens in practice today?',
      ex: {
        l: 'Example',
        t: "\"I get assigned a cold case. I look for the old file -- it's in storage. I wait 2 days, read hundreds of pages, make my own notes.\"",
      },
    },
    {
      id: 'workflow',
      sect: 'The Problem Today',
      type: 'textarea',
      text: "Describe how you'd want the new system to work -- step by step, from opening it to completing a task.",
      ex: {
        l: 'Example',
        t: '"I log in -> search by suspect name -> open the case -> see a timeline of everything -> attach my new notes -> flag for supervisor review -> close out."',
      },
    },
    {
      id: 'must_haves',
      sect: 'What You Need',
      type: 'textarea',
      text: "What features are absolutely essential? Without these you wouldn't use it.",
      ex: {
        l: 'Example',
        t: '"Search by name, date, location, or crime type. Attach and view photos and documents. Work on my department laptop."',
      },
    },
    {
      id: 'business_rules',
      sect: 'What You Need',
      type: 'textarea',
      text: 'What rules should the system automatically enforce or flag?',
      hint: 'Situations where the system should warn you, block an action, or require a second approval.',
      ex: {
        l: 'Example',
        t: '"Warn if I try to close a case with open evidence items. Block access to juvenile records unless assigned."',
      },
      required: false,
    },
    {
      id: 'edge_cases',
      sect: 'What You Need',
      type: 'textarea',
      text: 'What unusual situations could come up that the system needs to handle?',
      ex: {
        l: 'Example',
        t: '"Multiple suspects on the same incident. A suspect who is also a witness. Losing internet in the field mid-entry."',
      },
      required: false,
    },
    {
      id: 'nice_to_haves',
      sect: 'What You Need',
      type: 'textarea',
      text: 'What would be nice to have eventually but you could live without for now?',
      required: false,
    },
    {
      id: 'access_concerns',
      sect: 'Access & Security',
      type: 'textarea',
      text: 'Who in your agency should see what? Any records that need to be restricted?',
      ex: {
        l: 'Example',
        t: '"Patrol officers should not see active investigation details. Victim info restricted to assigned detective and supervisor."',
      },
    },
    {
      id: 'device_env',
      sect: 'Access & Security',
      type: 'single',
      text: 'How would officers primarily access this?',
      choices: [
        'Desktop computer at the station',
        'Laptop between station and field',
        'Mobile phone or tablet in the field',
        'A mix of all of these',
      ],
    },
    {
      id: 'data_sensitivity',
      sect: 'Access & Security',
      type: 'multi',
      text: 'What sensitive information will this system handle? Select all that apply.',
      choices: [
        'Criminal history / rap sheets (FBI/NCIC data)',
        'Victim personal information',
        'Witness identities',
        'Juvenile records',
        'Mental health or medical information',
        'Confidential informant information',
        'Evidence chain of custody',
        'Undercover operation details',
      ],
    },
    {
      id: 'existing_systems',
      sect: 'Current Systems',
      type: 'textarea',
      text: 'What systems do you currently use that this should connect to or replace?',
      ex: {
        l: 'Example',
        t: '"Tyler New World RMS. NCIC through a terminal. Separate evidence management. Everything else is paper or spreadsheets."',
      },
    },
    {
      id: 'training',
      sect: 'Practicalities',
      type: 'single',
      text: 'How much training time would officers realistically have?',
      choices: [
        '30 minutes or less -- must be that intuitive',
        '1-2 hours of formal training',
        'A half-day session',
        'Multiple days with ongoing support',
      ],
    },
    {
      id: 'success',
      sect: 'Practicalities',
      type: 'textarea',
      text: 'Six months after launch, how will you know this tool is actually helping?',
      ex: {
        l: 'Example',
        t: '"Detectives spend less time searching and more time investigating. Cold cases get re-opened that otherwise would have stayed cold."',
      },
    },
  ],
};
